#!/usr/bin/env ruby

require 'optparse'
require 'rubygems'
require 'hpricot'
require 'ruby-prof'

OPTIONS = {
  :environment => "production",
}

ARGV.options do |opts|
  script_name = File.basename($0)
  opts.banner = "Usage: ruby #{script_name} [options]"

  opts.separator ""

  opts.on("-e", "--environment=name", String,
          "Specifies the environment to create the account under (test/development/production).",
          "Default: production") { |OPTIONS[:environment]| }

  opts.separator ""

  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }

  opts.parse!
end

ENV["RAILS_ENV"] = OPTIONS[:environment]
require File.dirname(__FILE__) + "/../config/environment" 
require 'name_author'
require 'name_string'
require 'name_year'

def prepare_data
  df = File.open(File.dirname(__FILE__) + "/../dev_data/dev_names.xml") 
  get_data = false
  record = ""
  name = year = auth = url = ''
  df.readlines.each do |l|

    stripped = l.strip

    if stripped == "<Query17>"
      get_data = true
    elsif stripped == "</Query17>"
      get_data = false
      #TMP yield Hpricot(record)
      yield [name, auth, year, url]
      record = ""
    elsif get_data
      (tag,val) = stripped.match(/<([^>]+)>([^<]+)/)[1..2]
      name = val if tag.downcase == 'name'
      year = val if tag.downcase == 'year'
      auth = val if tag.downcase == 'author'
      url  = val if tag.downcase == 'url'
      record += l
    end
  end
end

c = ActiveRecord::Base.connection

%w(name_composites name_years name_authors name_strings).each do |table|
   c.execute("delete from #{table}")
end
count = 0
tm = Time.new
name_ids = {}
year_ids = {}
author_ids = {}
RubyProf.start
# SLOWER: (Hpricot(File.read(File.dirname(__FILE__) + "/../dev_data/dev_names.xml"))/"query17").each do |data|
#TMP: prepare_data do |data|
prepare_data do |name, author, year, url|
  count += 1
  if count % 10000 == 0 
    tm1 = Time.new
    delta = tm1 - tm
    tm = tm1
    puts count.to_s + " " + delta.to_s + "s"
  end
  #TMP author = (data/'author').inner_text.strip
  #TMP year = (data/'year').inner_text.strip 
  #TMP name = (data/'name').inner_text.strip
  #TMP url = (data/'url').inner_text.strip

  name_ids[name] ||= name == '' ? "null" : c.insert("insert into name_strings (name) values ('#{name}')") rescue  c.select_one("select id from name_strings where name = '#{name}'")['id']
  year_ids[year] ||= year == '' ? "null" : c.insert("insert into name_years (name_year) values ('#{year}')") rescue c.select_one("select id from name_years where name_year = '#{year}'")['id']
  author_ids[author] ||= author== '' ? "null" : c.insert("insert into name_authors (author_string) values ('#{author}')") rescue  c.select_one("select id from name_authors where author_string = '#{author}'")['id']
  composite_id = c.insert("insert into name_composites (name_author_id, name_year_id, name_string_id) values (#{name_ids[name]}, #{year_ids[year]}, #{author_ids[author]})") rescue puts("duplicate: name-#{name_ids[name]}, year-#{year_ids[year]}, author-#{author_ids[author]}")
#  ns = NameString.find_by_name(name) || NameString.create(:name => name)  
#  yr = NameYear.find_by_name_year(year.to_i) || NameYear.create(:name_year => year)
#  ath = NameAuthor.find_by_author_string(author) || NameAuthor.create(:author_string  => author)
#  cpn = NameComposite.create(:name_author => ath, :name_year => yr, :name_string => ns)
end
result = RubyProf.stop 

printer = RubyProf::FlatPrinter.new(result)
printer.print(STDOUT, 0)
